### ISSUE TITLE
Post installation guide

### ISSUE THREAD

**Issue by yashdharmamer** [paulrichards321/jpg2svs#1]
I used the instructions you've provided in the install.txt but I'm running into errors while trying to run the applications in the output folder.
`The application was unable to start correctly (0xc000007b)`
Could you provide some steps to follow to get the application running?
Also thank you for this resource, its the only open source attempt to create a .ini jpeg format reader.

**Comment by paulrichards321** [comment]
Hello!

It sounds like you might be mixing 32-bit and 64-bit libraries, or from an google search, you might just need to reboot your pc. Note this app has been tested to run on Windows 10, Windows 7 and Centos7/Redhat 7. What OS are you using? Can you also give me the output of pacman -Qqe? Did you try running on the command line in Msys2? When you do run Msys2, can you send me your path?
type on the command line:
echo $PATH

**Comment by paulrichards321** [comment]
Also note that the Gtk and Qt display program was just used for debugging and is very much alpha! If there is more of a demand for this I could spend more time on it. The actual convertor program, jpg2svs, does indeed work good in my experience for generating svs files from the jpeg files which can be displayed by ImageJ or Aperio's ImageScope app!

**Comment by yashdharmamer** [comment]
I really appreciate your prompt reply. I just require the converter actually. 
I'm on a Win7 machine and I've used the x86_64 ver of Msys2.
I tried the first few results I got after searching the error like rebooting my pc, installing .NET, updating my VC++ distributable etc, installing dlls. 
I'll be appending my results for pacman -Qqe and echo $PATH shortly

**Comment by yashdharmamer** [comment]
`
$ pacman -Qqe
asciidoc
autoconf
autoconf2.13
autogen
automake-wrapper
automake1.10
automake1.11
automake1.12
automake1.13
automake1.14
automake1.15
automake1.16
automake1.6
automake1.7
automake1.8
automake1.9
bash
bash-completion
bison
bsdcpio
bsdtar
bzip2
coreutils
curl
dash
diffstat
diffutils
dos2unix
dtc
file
filesystem
findutils
flex
gawk
gcc-libs
gdb
getent
gettext-devel
gperf
grep
groff
gzip
help2man
inetutils
info
intltool
lemon
less
libargp
libtool
libunrar
libunrar-devel
lndir
make
man-db
mercurial
mingw-w64-i686-binutils
mingw-w64-i686-cmake
mingw-w64-i686-crt-git
mingw-w64-i686-gcc
mingw-w64-i686-gcc-ada
mingw-w64-i686-gcc-fortran
mingw-w64-i686-gcc-libgfortran
mingw-w64-i686-gcc-libs
mingw-w64-i686-gcc-objc
mingw-w64-i686-gdb
mingw-w64-i686-headers-git
mingw-w64-i686-libmangle-git
mingw-w64-i686-libwinpthread-git
mingw-w64-i686-make
mingw-w64-i686-pkg-config
mingw-w64-i686-tools-git
mingw-w64-i686-winpthreads-git
mingw-w64-i686-winstorecompat-git
mingw-w64-x86_64-cmake
mingw-w64-x86_64-gcc
mingw-w64-x86_64-gcc-ada
mingw-w64-x86_64-gcc-fortran
mingw-w64-x86_64-gcc-objc
mingw-w64-x86_64-gdb
mingw-w64-x86_64-gtk3
mingw-w64-x86_64-libmangle-git
mingw-w64-x86_64-make
mingw-w64-x86_64-pkg-config
mingw-w64-x86_64-qt5
mingw-w64-x86_64-tools-git
mingw-w64-x86_64-winstorecompat-git
mintty
msys2-keyring
msys2-launcher-git
msys2-runtime
ncurses
pacman
pacman-mirrors
pactoys-git
patch
patchutils
pax-git
pkg-config
pkgfile
quilt
rcs
rebase
scons
sed
subversion
swig
texinfo
texinfo-tex
tftp-hpa
time
ttyrec
tzcode
unrar
util-linux
which
xmlto
`
`
$ echo $PATH
/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
`

**Comment by paulrichards321** [comment]
Hello,

Did you get a compiler error previously? I did when I used the git version. I had done some updates on my PC but had not pushed it to git yet, mostly because I didn't think anyone was using this, lol. Delete your jpg2svs directory and do a fresh git:
```
git clone https://github.com/paulrichards321/jpg2svs
cd jpg2svs
make
# make sure you don't get an error compiling... if all goes well do the following:
cd output/bin
./jpg2svs.exe inputfolder outputfile
# make sure to include the .exe in the file filename, otherwise it tries to execute the linux binary
# syntax: jpegtosvs.exe -h[0,1] -x[bestXOffset] -y[bestYOffset] -z[0,1] <inputfolder> <outputfile>
# note that with msys2 you will need to use a double \\ for folders for instance, if your output file is on the j:\ drive:
# ./jpg2svs.exe somejpgfolder j:\\someoutputfile.svs
```

**Comment by paulrichards321** [comment]
Few more things:
From the pacman -Qqe output, I think you missed that part in the instructions where you install opencv. It appears that you don't have opencv installed. You will need to download that as well:
`pacman -S mingw64/mingw-w64-x86_64-opencv
`
Also, just to be safe run g++ -v and make sure you get the 64 bit version of gcc
`g++ -v
`
Somewhere in the output of the above command you should have:
`Target: x86_64-w64-mingw32
`

**Comment by yashdharmamer** [comment]
It works well! I really appreciate your guidance on this.
I faced no errors while converting to both .svs and .tiff formats using the program.
